import * as fs from 'node:fs';
import * as path from 'node:path';
import type { FullConfig, FullResult, Reporter, Suite, TestCase, TestResult } from '@playwright/test/reporter';

/**
 * Builds a requirements-traceability matrix from the run itself:
 *   user story (from @US-xxx tags) → tests → outcome → linked BUG ids (from knownBug()).
 *
 * Outputs (always): test-results/summary.json and test-results/traceability.md.
 * With UPDATE_DOCS=1 it also refreshes docs/traceability.md. Only do that on a full run,
 * so a partial `-g` run never overwrites the committed matrix with partial data.
 *
 * summary.json is what the CI workflow publishes next to each HTML report and what the
 * trigger UI reads to show "131 passed · 17 known bugs · p95 1022 ms" per run.
 */
type Row = { id: string; story: string; title: string; project: string; outcome: string; bugs: string[]; durationMs: number };

const STATUS_ICON: Record<string, string> = { expected: '✅', 'known-bug': '🐞', flaky: '⚠️', unexpected: '❌', skipped: '⏭️' };

class TraceabilityReporter implements Reporter {
  private rows: Row[] = [];
  private annotations: Record<string, string> = {};
  private started = Date.now();
  private rootDir = process.cwd();

  onBegin(config: FullConfig, _suite: Suite) {
    // Not config.rootDir: that's the testDir (./tests), not the repo root.
    this.rootDir = config.configFile ? path.dirname(config.configFile) : process.cwd();
  }

  onTestEnd(test: TestCase, result: TestResult) {
    if (result.retry < test.results.length - 1) return; // only the final attempt counts
    const stories = test.titlePath().join(' ').match(/@US-\d{3}/g) ?? ['(untagged)'];
    const bugs = test.annotations.filter((a) => a.type === 'known-bug').map((a) => a.description!.split(':')[0]);
    let outcome: string = test.outcome();
    if (outcome === 'expected' && test.expectedStatus === 'failed') outcome = 'known-bug';
    for (const a of test.annotations) {
      if (['p95', 'LCP', 'page-weight', 'fast-3g'].includes(a.type) && a.description) this.annotations[`${a.type}:${test.title}`] = a.description;
    }
    const project = test.parent.project()?.name ?? '';
    for (const s of new Set(stories)) {
      // Title alone isn't unique (e.g. "/ has no horizontal overflow" exists per viewport),
      // so show the describe path and key rows by Playwright's stable test id.
      const title = test.titlePath().slice(3).join(' › ');
      this.rows.push({ id: test.id, story: s.replace('@', ''), title, project, outcome, bugs, durationMs: result.duration });
    }
  }

  async onEnd(result: FullResult) {
    const unique = new Map<string, Row>();
    for (const r of this.rows) unique.set(r.id, r); // a test tagged with 2 stories counts once
    const tests = [...unique.values()];
    const count = (o: string) => tests.filter((t) => t.outcome === o).length;
    const bugIds = [...new Set(tests.flatMap((t) => t.bugs))].sort();

    const summary = {
      status: result.status,
      startedAt: new Date(this.started).toISOString(),
      durationMs: Date.now() - this.started,
      totals: {
        tests: tests.length,
        passed: count('expected'),
        knownBugs: count('known-bug'),
        flaky: count('flaky'),
        failed: count('unexpected'),
        skipped: count('skipped'),
      },
      byProject: Object.fromEntries(
        [...new Set(tests.map((t) => t.project))].map((p) => [p, tests.filter((t) => t.project === p).length]),
      ),
      bugsConfirmedThisRun: bugIds,
      metrics: this.annotations,
    };

    const stories = [...new Set(this.rows.map((r) => r.story))].sort();
    const lines = [
      '# Traceability Matrix',
      '',
      `> Generated by \`reporters/traceability-reporter.ts\` from the run at ${summary.startedAt}. Run status: **${result.status}**.`,
      '',
      `**${summary.totals.tests} tests** · ✅ ${summary.totals.passed} passed · 🐞 ${summary.totals.knownBugs} failing on a documented bug · ⚠️ ${summary.totals.flaky} flaky · ❌ ${summary.totals.failed} unexpected failures`,
      '',
      'Legend: ✅ passed · 🐞 fails as expected because of a documented bug (see `docs/bugs.md`) · ⚠️ passed on retry · ❌ unexpected failure',
      '',
      '| Story | Tests | ✅ | 🐞 | ⚠️ | ❌ | Linked bugs |',
      '|---|---|---|---|---|---|---|',
      ...stories.map((s) => {
        const r = this.rows.filter((x) => x.story === s);
        const n = (o: string) => r.filter((x) => x.outcome === o).length;
        const bugs = [...new Set(r.flatMap((x) => x.bugs))].sort().join(', ') || '—';
        return `| ${s} | ${r.length} | ${n('expected')} | ${n('known-bug')} | ${n('flaky')} | ${n('unexpected')} | ${bugs} |`;
      }),
      '',
      '## Bug → test links',
      '',
      '| Bug | Tests that reproduce it |',
      '|---|---|',
      ...bugIds.map((b) => `| ${b} | ${tests.filter((t) => t.bugs.includes(b)).map((t) => `\`${t.project}\` ${t.title}`).join('<br>')} |`),
      '',
      '<details><summary>Every test</summary>',
      '',
      '| Story | Project | Test | Result |',
      '|---|---|---|---|',
      ...this.rows.sort((a, b) => a.story.localeCompare(b.story)).map((r) => `| ${r.story} | ${r.project} | ${r.title.replace(/\|/g, '\\|')} | ${STATUS_ICON[r.outcome] ?? r.outcome}${r.bugs.length ? ' ' + r.bugs.join(', ') : ''} |`),
      '',
      '</details>',
      '',
    ];

    const outDir = path.join(this.rootDir, 'test-results');
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(path.join(outDir, 'summary.json'), JSON.stringify(summary, null, 2));
    fs.writeFileSync(path.join(outDir, 'traceability.md'), lines.join('\n'));
    if (process.env.UPDATE_DOCS === '1') {
      try {
        fs.writeFileSync(path.join(this.rootDir, 'docs', 'traceability.md'), lines.join('\n'));
      } catch (err) {
        // A reporting problem must never turn a test run red.
        console.warn(`[traceability] could not update docs/traceability.md: ${(err as Error).message}`);
      }
    }
  }

  printsToStdio() {
    return false;
  }
}

export default TraceabilityReporter;
